#Trying to go to the faster container infrastructure of github
sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.5
      env: deps=low

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - deps=no
    - secure: "TaQTGgMHcaejJfKyuHeT7YAc6ysT+xT6j6SEvSKfjIPkroJE/ZXDRdMevTIlkmPz7InLWmWksZ8mfb3ZlFtOYF9H5N88XTuSMCf3Ce+FY8yQNAxLimtpN5qXQ3jLuDLhsG2eI8r/9bIK6Amx9g4GRVeDOvCwJ3lfiaipMRPNKZY="

install:
  - if [ "$deps" = "no" ]; then composer install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit

before_install:
  - travis_retry composer self-update
  - composer config --quiet github-oauth.github.com $GITHUB_TOKEN
  - if [[ ! $GITHUB_TOKEN ]]; then echo "no github token"; fi

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then php vendor/bin/coveralls -v ; fi
  - if [[ $TRAVIS_PHP_VERSION != '7.0' ]] && [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
