
#name: "Backward Compatibility Check"

#on:
#  pull_request:

#jobs:
#  roave_bc_check:
#    name: "Roave BC Check"
#    runs-on: "ubuntu-20.04"
#    steps:
#      - uses: "actions/checkout@v2"
#        with:
#          fetch-depth: 0

#      - name: "Roave BC Check"
#        uses: "docker://nyholm/roave-bc-check-ga"
#        with:
#          args: "--from=${{ github.event.pull_request.base.sha }}"
